from infrastructure.embeddings.text.openai_text import OpenAITextEmbedding
from infrastructure.embeddings.text.ark_text import ArkTextEmbedding

from infrastructure.embeddings.image.ark_image import ArkImageEmbedding